[package]
name = "genpass"
version = "0.1.0"
authors = ["Cyryl Płotnicki <cyplo@cyplo.net>"]
description = "A simple yet robust commandline random password generator."
license-file = "LICENSE"
repository = "https://github.com/cyplo/genpass"

[dependencies]
rand = "0.4.2"

[dev-dependencies]
quickcheck = "0.6.2"