[package]
name = "genpass"
version = "0.1.0"
authors = ["Cyryl Płotnicki <cyplo@cyplo.net>"]
description = "A simple yet robust commandline random password generator."
repository = "https://github.com/cyplo/genpass"
license-file = "LICENSE"
readme = "README.md"

[badges]
travis-ci = { repository = "cyplo/genpass", branch = "master" }

[dependencies]
rand = "0.4.2"

[dev-dependencies]
quickcheck = "0.6.2"